### ISSUE TITLE
Ammo Problems

### ISSUE THREAD

**Issue by Gameadictive** [friped/fdev_weapons#3]
When i buy the weapon in the police shop i get a 100 ammo pistol, then i buy for example 20 bullets and the pistol convert in a 20 ammo pistol.

Then i drop the 20 ammo pistol on floor and this drop with 100 bulets then i take the pistol and is with 100 ammo and i have 100 ammo

Did you know why ?

**Comment by friped** [comment]
Are you using both ordinary weapons and this script?

**Comment by Gameadictive** [comment]
It seems like yes
u know how to disable?
